apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.cassandra.secret.name }}"
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  cassandra-password: "{{ .Values.cassandra.secret.value }}"